// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK1HwEzXFab-Aex64E7N1HPUHhP_86LN4',
    appId: '1:582973803832:web:15edacd556b709ec3105cd',
    messagingSenderId: '582973803832',
    projectId: 'meal-planner-6d481',
    authDomain: 'meal-planner-6d481.firebaseapp.com',
    storageBucket: 'meal-planner-6d481.firebasestorage.app',
    measurementId: 'G-HEZMW4KF64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuZl9cnp2mgxCrC9Jx-80x7mrnQQ0Ur2I',
    appId: '1:582973803832:android:ab9687b7bcd7b3093105cd',
    messagingSenderId: '582973803832',
    projectId: 'meal-planner-6d481',
    storageBucket: 'meal-planner-6d481.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ7ydm05qadLobRD0aqiOG9SXuhydfRjw',
    appId: '1:582973803832:ios:7087cb3efb8117183105cd',
    messagingSenderId: '582973803832',
    projectId: 'meal-planner-6d481',
    storageBucket: 'meal-planner-6d481.firebasestorage.app',
    iosClientId: '582973803832-df5mrg1uc8itrffifmf3h8og2a440mk8.apps.googleusercontent.com',
    iosBundleId: 'com.example.dietSuggestion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ7ydm05qadLobRD0aqiOG9SXuhydfRjw',
    appId: '1:582973803832:ios:7087cb3efb8117183105cd',
    messagingSenderId: '582973803832',
    projectId: 'meal-planner-6d481',
    storageBucket: 'meal-planner-6d481.firebasestorage.app',
    iosClientId: '582973803832-df5mrg1uc8itrffifmf3h8og2a440mk8.apps.googleusercontent.com',
    iosBundleId: 'com.example.dietSuggestion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDK1HwEzXFab-Aex64E7N1HPUHhP_86LN4',
    appId: '1:582973803832:web:6f06a62c4a8db7f63105cd',
    messagingSenderId: '582973803832',
    projectId: 'meal-planner-6d481',
    authDomain: 'meal-planner-6d481.firebaseapp.com',
    storageBucket: 'meal-planner-6d481.firebasestorage.app',
    measurementId: 'G-SWJYD5VGSW',
  );
}
